[mypy]
ignore_missing_imports = True
install_types = True
non_interactive = True

# Проверяем только основной код
files = aaps_emulator/, core/, runner/

# Игнорируем тесты и инструменты
exclude = (tests/|tools/|visual/|setup\.py|run\.py)
